# Generated by Django 4.0.5 on 2022-06-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[(1, 'RadioButton'), (2, 'CheckBox'), (3, 'Select')], default=1, max_length=32),
        ),
    ]
