# Generated by Django 4.0.5 on 2022-06-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_question_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.IntegerField(choices=[(1, 'RadioButton'), (2, 'CheckBox'), (3, 'Select')], default=1),
        ),
    ]
