# Generated by Django 4.0.5 on 2022-06-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_submission_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='phone',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
